config/routes.rb
require 'sidekiq/web'
# == Route Map (Updated 2013-02-05 08:34)
#

Sm::Application.routes.draw do

  root to: 'web/home#index', url: 'samara-market.com'
  scope module: :web  do

    controller :categories, path: 'catalog', format: false do
      get '/:category_id(/page/:page)' => redirect{|params| "/catalog/#{params[:category_id]}.html"}
    end

    controller :notification, path: :notification, format: false do
      post :qiwi, action: :qiwi
    end

    controller :categories, path: 'catalog', format: true, constraints: {format: /(html)/} do
      get '/:category_id(/page/:page)', action: :show, as: :category
      get '/', action: :index, as: :categories
    end
    get 'catalog'  => redirect{|params| "/catalog.html"}
    resources :orders, only:[:new, :create, :index, :show]


    controller :cart do
      get 'cart', action: :index, format: true, constraints: {format: /(html)/}
      post 'cart/set_count', action: :set_count, as: 'cart_set_count'
      put 'cart/push', action: :push, as: 'add_to_cart'
      delete 'cart/pop', action: :pop, as: 'remove_from_cart'
      delete 'cart/destroy_products', action: :destroy, as: 'destroy_from_cart'
    end

    controller :brand, format: true, constraints: {format: /(html)/} do
      get '/brands/:id', action: :show, as: :brand
      get '/brands/:brand_id/products(/page/:page)', action: :products, as: 'brand_products'
      get '/brands', action: :index, as: :brands
    end

    controller :types, format: true, constraints: {format: /(html)/} do
      get '/types/:id', action: :show, as: :type
      get '/types/:type_id/products(/page/:page)', action: :products, as: 'type_products'
      get '/types', action: :index, as: :types
    end
    resources :addresses, only: [:index, :update, :destroy, :edit, :new, :create]

    resources :contacts, only: [:index, :create], format: true, constraints: {format: /(html)/}
    get '/viewed_products', constraints: {format: /(html)/}, format: true, controller: :categories, action: :viewed, as: :viewed_products
    get '/discounts(/page/:page)', constraints: {format: /(html)/}, format: true, controller: :categories, action: :discounts, as: :discounts

    resources :products, only: [:show], path: 'product',
      format: true, constraints: {format: /(html)/} do
      resources :reviews, only: [:create], format: false, constraints: {format: nil} do |variable|
        post '/vote_up', action: :vote_up
        post '/vote_down', action: :vote_down
        collection do
          get '/is_edit', action: 'edit?'
          delete '/', action: :destroy
        end
      end
    end

    controller :search, format: true, constraints: {format: /(html)/} do
      get '/search', action: :index, as: :search
    end


    controller :sessions do
      get '/user/is_auth', action: 'auth?'
      get '/user/logout', action: 'logout'
      post '/user/login', action: 'login'
      get '/user/login', action: 'login_page'
      match '/auth/:provider/callback', action: 'oauth'
    end

    controller :user do
      get '/user', action: :index
      post '/user', action: :create
      put '/user', action: :update, as: :update_user
      get '/user/data_verified/:field', action: :data_verified?, as: :data_verified_field, constraints: {field: /(phone|email)/}
      post '/user/data_verified/:field', action: :data_verified, constraints: {field: /(phone|email)/}, as: :data_verified
      get '/recovery_password', as: :recovery_password, action: :recovery_password
      post '/recovery_password', action: :recovery_password!
      post '/update_password', action: :update_password
    end

    controller :sitemap do
      get '/sitemap', action: :index, format: true, constraints: {format: /(xml)/}, as: 'sitemap'
      get '/sitemap_products', action: :products, format: true, constraints: {format: /(xml)/}, as: 'sitemap_products'
      get '/sitemap_categories', action: :categories, format: true, constraints: {format: /(xml)/}, as: 'sitemap_categories'
      get '/sitemap_brands', action: :brands, format: true, constraints: {format: /(xml)/}, as: 'sitemap_brands'
    end

    controller :static_content, format: true, constraints: {format: /(html)/} do
      get '/public_offer', action: 'public_offer'
      get '/privacy_policy', action: 'privacy_policy'
      get '/return_of_goods', action: 'return_of_goods'
      
    end

    controller :delivery, format: true, constraints: {format: /(html)/} do
      get '/delivery', action: :index, as: :delivery
    end

    controller :payment, format: true, constraints: {format: /(html)/} do
      get '/payments', action: :index, as: :payments
    end

  end


  namespace :admin, path: 'the_simpsons_admin' do

    resources :categories, only: [:index, :create, :update, :destroy, :show] do
      resources :adwords, controller: 'CategoriesAdwords' do
        post 'image', action: 'image'
        post 'background', action: 'background'
        post 'cover', action: 'cover'
        post :position, action: :position
      end
      collection do
        put ':id/position', action: :position
        get ':id/products', action: :products
      end
    end
    resources :adwords, only: [:index]
    resources :products_types, only: [:index, :create, :update, :destroy, :show] do
      get :products, action: :products
      resources :type_property, only: [:index, :create, :update, :destroy, :show] do
        collection do
          post ':id/position', action: :position
        end  
      end
    end

    resources :products_suppliers, only: [:index, :create, :update, :destroy, :show] do
      get :products, action: :products
    end
    resources :brands, only: [:index, :create, :update, :destroy, :show] do
      post 'logo', action: 'upload_logo'
      delete  'logo', action: 'destroy_logo'
      get :products, action: :products 
    end
    resources :products_groups, only: [:index, :create, :update, :destroy, :show] do
      get :products, action: :products
    end
    resources :products, only: [:index, :create, :update, :destroy, :show] do
      put :discount, action: 'create_discount'
      delete :discount, action: 'destroy_discount'
      put :item, action: 'create_item'
      delete 'item/:id', action: 'destroy_item'
      resources  :images, controller: :product_image , only: [:create, :destroy] do
        put :cover, action: :cover
        post :position, action: :position
      end
      resources :products_property, only: [:create, :update, :destroy] do 
        resources :products_property_value, only: [:create, :update, :destroy]
      end

      collection do
        put ':id/categories', action: :set_categories
        get ':id/categories', action: :get_categories
      end   
    end
    resources :articles, only: [:index, :update, :show, :create, :destroy] do
      post '/image', action: :image_upload
      delete '/image', action: :image_destroy
      get '/images', action: :images
    end
    resources :orders, only: [:index, :update, :show] do
      get '/bill', action: :bill
      get '/invoice', action: :invoice
      put :bil_qiwi, action: :bil_qiwi
    end
    controller :main do
      get '/login', as: :login, action: :login
      post '/login', action: :auth
      get '/logout', as: :logout, action: :logout
      get '/expire_sitemap', as: :expire_sitemap, action: :expire_sitemap
    end
    get 'properties_values', controller: :ProductsProperty , action: 'properties_values'
    root to: 'main#index' 

  end
  

end

app/models/category_views.rb
class CategoryViews < ActiveRecord::Base
  attr_accessible :token, :category_id
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  def index
    @categories = Category.includes(:adwords).tree
    render json: @categories
  end
  def show
    @category = Category.find(params[:id])
    render json: @category.to_json(include:[:adwords])
  end
  def create
    @category = Category.new(params[:category])
    if @category.save
      render json: @category, status: :created
    else
      render json: @category.errors, status: :unprocessable_entity 
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      render json: {status: true}
    else
      render json: @category.errors, status: :unprocessable_entity 
    end
  end
  def destroy
    @category = Category.find(params[:id])
    if @category.id != 1
      @category.destroy
    end 
    head :no_content
  end
  def position
    @category = Category.find(params[:id])
    if params[:position] == 'before'
      @category.move_to_left_of(params[:neighbor])
    elsif params[:position] == 'after'
      @category.move_to_right_of(params[:neighbor])
    end  
    render json: {status: true}
  end
  def products
    @category = Category.find(params[:id])
    render json: @category.products
      .select('products.id, products.name, products.status, products.type_id, products.brand_id, products.price, products.discount_type_id, products.discount_value')
      .to_json(only:[:id, :name, :status, :type_id, :brand_id], methods: :real_price)
  end
end

app/controllers/web/categories_controller.rb
class Web::CategoriesController < Web::ApplicationController

  #before_filter :normalize_brend_params, only: [:show]

  helper_method :normalize_brend_params, :sorting_products, :normalize_types_params

  def index
    @categories = Category.select('id, name, link_rewrite, depth, parent_id, lft, rgt, types_ids, products_visible').public.tree
  end

  def show

    params[:filters] = {} unless params[:filters].instance_of? ActiveSupport::HashWithIndifferentAccess

    category = Category.public.find_by_link_rewrite(params[:category_id]) || not_found
    
    
    properties = []

    if category.types_ids.to_a.count == 1 or params[:filters][:types].to_a.count == 1
      if category.types_ids.to_a.count == 1
        current_type = category.types_ids.to_a[0]
      else
        current_type = params[:filters][:types].to_a[0]
      end 
      properties = ProductsType.find(current_type).properties.select([:id, :name, :unit]).where(is_filter: true).order(:position)
    end
    @query = Product.search(
        include: :cover,
        select: 'products.id,
          products.name, products.link_rewrite, products.cover_id, products.status,
          products.price, products.brand_id, products.ratio, products.ratio_u, products.discount_type_id, products.discount_value',
      ) do
      with :categories_ids, category.id

      with :status, 20..30     

      facet_exclude = []
      facet_exclude.push with(:brand_id, params[:filters][:brands].map{|x| x.to_i}) unless params[:filters][:brands].blank?
      facet_exclude.push with(:type_id, params[:filters][:types].map{|x| x.to_i}) unless params[:filters][:types].blank?

      if properties.count > 0
        
        dynamic(:properties) do
          properties.each do |prop|
            q = nil
            q = with(prop.id.to_s, params[:filters][prop.id.to_s]) unless params[:filters][prop.id.to_s].blank?
            facet prop.id, exclude: q, zeros: true
            facet_exclude.push q if q
          end
        end
      end

      facet :brand_id, exclude: facet_exclude

      facet :type_id, exclude: facet_exclude


      order_by :status, :desc
      case params[:sort]
        when 'news'
          order_by :id, :desc
        when 'cheap'
          order_by :real_price
        when 'discount_first'
          order_by :discount_type_id, :desc
          order_by :real_price, :desc
        when 'az'
          order_by :name
        when 'za'
          order_by :name, :desc
        else
          order_by :real_price, :desc
      end
      if params[:page] and params[:page].to_i > 0
        paginate page: params[:page].to_i 
      end
      
    end
    @category = category
    @properties = properties
    @products = @query.results
    @types = ProductsType.order(:name).select([:id, :name]).find(@query.facet(:type_id).rows.map{|x| x.value})
  end

  def discounts

    @brands_ids = Product.only_discount.uniq.pluck('brand_id')
    @types_ids = Product.only_discount.uniq.pluck('type_id')

    @filter = {
      brands: normalize_brend_params(@brands_ids),
      types: normalize_types_params(@types_ids),
      sort: nil
    }

    @filter[:sort] = case params[:sort]
      when 'cheap'
        :discount_first_asc
      when 'az'
        :az
      when 'za'
        :za
      when 'news'
       :news
      when 'expensive'
        :discount_first
      else
        :amount_of_discount
    end

    @products = Product.joins(:brand).select('products.id,
      products.name, products.link_rewrite, products.cover_id, products.status,
      products.price, products.brand_id, brands.name AS `brand_name`, products.ratio, products.ratio_u, products.discount_type_id, products.discount_value').order('products.status DESC')
      .sorting(@filter[:sort]).only_discount.visible().includes(:cover).page(params[:page])

    @products = @products.brands(@filter[:brands]) if @filter[:brands]
    @products = @products.where(type_id: @filter[:types]) if @filter[:types]

    respond_to do |format|
      format.html do
        @brands = Brand.where(id: @brands_ids).select('id, name')
        @types = ProductsType.where(id: @types_ids).select('id, name')
      end
      format.json { render json: category } 
    end
  end

  def viewed
    @viewed_ids = cookies[:viewed_products].to_s.split(",")

    ids = Product.select('brand_id, type_id').visible().where(id: @viewed_ids).limit(30)

    brand_ids = ids.collect{|x| x.brand_id}.uniq
    type_ids = ids.collect{|x| x.type_id}.uniq

    @filter = {
      brands: normalize_brend_params(brand_ids),
      sort: sorting_products(params[:sort]),
      types: normalize_types_params(type_ids)
    }

    @products = Product.joins(:brand).select('products.id,
      products.name, products.link_rewrite, products.cover_id, products.status,
      products.price, products.brand_id, brands.name AS `brand_name`, products.ratio, products.ratio_u, products.discount_type_id, products.discount_value').order('products.status DESC')
      .sorting(@filter[:sort]).visible().includes(:cover).where(id: @viewed_ids).limit(30)

    @products = @products.brands(@filter[:brands]) if @filter[:brands]
    @products = @products.where(type_id: @filter[:types]) if @filter[:types]
    
    respond_to do |format|
      format.html do
        @brands = Brand.where(id: brand_ids).select('id, name')
        @types = ProductsType.where(id: type_ids).select('id, name')
      end
      format.json { render json: category } 
    end
  
  end

  private

    def normalize_brend_params(real_brands)
      brands = nil
      if params[:brands]
        params[:brands] = (params[:brands].to_a.collect{|x| x.to_i if x.to_i > 0}).compact
        params[:brands] = (params[:brands].size > 0) ? params[:brands] : nil
        brands = (params[:brands] & real_brands)
      end
      return brands ? brands : nil
    end

    def normalize_types_params(real_types)
      types = nil
      if params[:types]
        params[:types] = (params[:types].to_a.collect{|x| x.to_i if x.to_i > 0}).compact
        types = (params[:types].size > 0) ? params[:types] : nil
      end
      return types ? types : nil
    end

    def sorting_products(sort)
      case sort
        when 'cheap'
          :cheap
        when 'az'
          :az
        when 'za'
          :za
        when 'news'
          :news
        when 'discount_first'
          :discount_first
        else
          nil
        end
    end

end

app/helpers/web/categories_helper.rb
module Web::CategoriesHelper



end

app/views/web/categories/discounts.html.haml
- content_for(:head) do

  %title 
    Скидки | интернет магазин Самара-Маркет
    = "-страница #{params[:page].to_i}" if params[:page].to_i > 1

  %meta{name: 'description', content: 'Всё товары со скидками от интернет магазина Самара-Маркет'+(" -страница #{params[:page].to_i}" if params[:page].to_i > 1).to_s}

  %meta{name: 'keywords', content: 'интернет,магазин,скидки,дешего,дешево,дешевле,скидок,цена,предложение,подешевле,со скидками'}

  %link{rel: :canonical, href: discounts_path( format: :html, only_path: false, page: params[:page])}

  :javascript
    config.navigation = true
.products_page
  .pageWrap
    .pageContainer
      .columnRight
        .content
          %h1 Товары со скидками
          %ul#sorting.nav.nav-tabs
            %li.title
              Сортировать: 
            %li{class: ('active' if @filter[:sort]==:news) }
              %a{href: discounts_path(format: :html, brands: @filter[:brands], types: @filter[:types], sort: :news, page: nil)}
                Новые
            %li{class: ('active' if @filter[:sort]==:amount_of_discount) }
              %a{href: discounts_path(format: :html, brands: @filter[:brands], types: @filter[:types], sort: nil, page: nil)}
                По размеру скидки
            %li{class: ('active' if @filter[:sort]==:discount_first) }
              %a{href: discounts_path(format: :html, brands: @filter[:brands], types: @filter[:types], sort: 'expensive', page: nil)}
                Дорогие
            %li{class: ('active' if @filter[:sort]==:discount_first_asc) }
              %a{href: discounts_path(format: :html, brands: @filter[:brands], types: @filter[:types], sort: 'cheap', page: nil)}
                Подешевле
            %li{class: ('active' if @filter[:sort]==:az) }
              %a{href: discounts_path(format: :html, brands: @filter[:brands], types: @filter[:types], sort: 'az', page: nil)}
                А-я
            %li{class: ('active' if @filter[:sort]==:za) }
              %a{href: discounts_path(format: :html, brands: @filter[:brands], types: @filter[:types], sort: 'za', page: nil)}
                Я-а
          -if @products.count == 0
            %h2
              К сожалению, скидок, пока, нет
          -else
            .block_products_block.thumbnails.simple
              =render partial: 'web/products/preview', collection: @products, as: :product
              = paginate @products, theme: :products, window: 4, outer_window: 1
              - content_for(:after_body) do
                :javascript
                  $(document).ready(function(){
                  ObserveResize.getInstance().add('resize_block_products_block',Helper.resize_block_products_block)
                  })
      .columnLeft
        =render partial: 'web/products/filters/brands_for_discounts', locals: { filter: @filter[:brands] }
        =render partial: 'web/products/filters/types_for_discounts'

      .clearfix.clear

app/views/web/categories/index.html.erb
<% content_for(:head) do %>
  <title>Каталог интернет магазина Самара-Маркет</title>
  <meta name="description" content="Каталог интернет магазина Самара-Маркет. Бытовая техника для кухни и дома, каталог Красота и здоровье, посуда и другие товары для кухни. Товары для животных">
  <meta name="keywords" content="каталог,интернет магазин,купить,в самаре,<%=@categories.collect{|x| x.name}.join(',') %>">
  <link rel="stylesheet" href="<%= categories_url(format: :html, only_path: false) %>">
<% end %>
<div class="all_catalog page_single_row">
  <h1>Каталог интернет магазинга</h1>

  <% cache('catalog_page_'+Category.maximum('updated_at').to_i.to_s)  do %>
    <% categories = {}; @categories.each{|x| categories[x.id] = x }; @categories = nil %>
    <% open_box = false %>
    <% not_print_categories = [] %>
    <% categories.values.each do |category| %>
      <% if category.depth == 1 %>
        <% if open_box %>
          </ul>
          <% open_box = false %>
        <% end %>
        <h2>
          <%= link_to category.name, category_path(category.link_rewrite,format: :html, page: nil) %>
        </h2>
        <% if category.last_depth? %>
          <% products = category.products.select('products.id, products.name, products.link_rewrite, products.cover_id, products.price, products.status, products.brand_id, brands.name AS `brand_name`, products.discount_type_id, products.discount_value').joins(:brand).visible.order_stock.order_by_last_views.includes( :cover).limit(10) %>
          <% if products.any? %>
            <div class="category_box_x simple">
              <div class="wrap">
                <%= render partial: 'web/products/simple_preview', collection: products, as: :product %>
              </div>
            </div>
          <% end %>
        <% else %>
          <% open_box = true %>
          <ul class="thumbnails category_prew">
        <% end %>
      <% else %>
        <% unless not_print_categories.include?(category.id) or category.types_ids.to_a.count == 0 and category.depth < 5 %>
          <% if !category.last_depth? and category.depth > 2 %>
            <% childrens = categories.values.keep_if{|x| x.parent_id == category.id} %>
            <% b = [] %>
            <% childrens.each{|x| b += x.types_ids} %>

            <% if (category.types_ids - b).count != 0 %>
              <% not_print_categories += childrens.map{|x| x.id} %>
            <% else %>
              <% not_print_categories.push(category.id) %>

            <% end %>
          <% end %>
          <% unless not_print_categories.include?(category.id) %>
            <li class="thumbnail <% if category.depth == 2 %><% if category.last_depth? %>super<% else %>well<% end %><% end %>">
              <% if category.depth == 2 and !category.last_depth? %>
                <p class="super-title"><%= link_to category.name, category_path(category.link_rewrite,format: :html, page: nil) %></p>

              <% else %>
                <p class="title"><%= link_to "#{category.name} (#{category.products_visible.to_i.to_s})", category_path(category.link_rewrite,format: :html, page: nil), title: 'Категория '+category.name %></p>
                <% product = category.products.select('products.id, products.cover_id, products.price').visible.expensive.first %>
                <% if product and product.cover %>
                  <%= link_to category_path(category.link_rewrite,format: :html, page: nil), title: 'Категория '+category.name do %>
                    <img src="<%= product.cover.image.thumb_200.url %>" alt="каталог <%= category.name %>">
                  <% end %>
                <% end %>
              <% end %>
            </li>
          <% end %>
        <% end %>

      <% end %>  
    <% end %>
  <% end %>
</div>
<script>
  $(document).ready(function(){
    ObserveResize.getInstance().add('resize_block_category_products',Helper.resize_block_category_products);
    ObserveResize.getInstance().add('resize_block_category_prew',function(){
      c_width = window._$.container.width()-15
      $('.category_prew .thumbnail').width((c_width/Math.floor(c_width/225))-20)
    });
  })
</script>

app/views/web/categories/show.html.haml
- promo_adwords = CategoryAdvertising.where("category_id=#{@category.id} and image IS NOT NULL #{'and id <> '+@category.adword_id.to_s if @category.adword_id}").to_a

- content_for(:head) do

  %title 
    = @category.name
    =('cтраница '+params[:page].to_s if params[:page].to_i > 0).to_s
  :css
    .category_description {
      max-width: 800px;
    }
  %meta{name: 'description', content: 'Каталог '+@category.name+' в интернет магазине Самара-Маркет. Цены на '+@category.products_visible.to_s+Russian.p(@category.products_visible, ' товара.', ' товаров.', ' товаров.')+(' Страница '+params[:page].to_s if params[:page].to_i > 0).to_s}

  %meta{name: 'keywords', content: 'каталог,'+@category.name+','+@category.meta_keywords.to_s+','+(@types.map {|x| x.name}).join(',')}

  %link{rel: :canonical, href: category_url(@category.link_rewrite, format: :html, only_path: false, page: params[:page])}

  :javascript
    config.navigation = true
.products_page
  .pageWrap
    .pageContainer
      .columnRight
        .content
          =render partial: 'web/breadcrumbs/categories', locals: {category: @category}

          %h1
            =@category.name
          -unless promo_adwords.empty?

            =render partial: 'web/adword/carousel', locals: {adwords: promo_adwords}
          - categories = @category.children.select('id,name,link_rewrite, lft, rgt, products_visible').where('products_visible > 0').public
          -if @category.depth < 3 and !@category.last_depth? and params[:filters][:brands].nil? and params[:filters][:types].nil?
            -if categories.count > 5
              .all_catalog
                %ul.thumbnails.category_prew
                  -categories.each do |category|
                    %li.thumbnail
                      %p.title= link_to "#{category.name} (#{category.products_visible})", category_path(category.link_rewrite,format: :html, page: nil), title: category.name
                      =link_to category_path(category.link_rewrite,format: :html, page: nil), title: category.name do
                        %img{src: category.products.select('products.id, products.cover_id, products.price').where('products.cover_id > 0').visible.expensive.first.cover.image.thumb_200.url, title:category.name}
              %script
                $(document).ready(function(){(function(){fn=function(){c_width=$(".all_catalog:first").width()-5;$(".category_prew .thumbnail").width((c_width/Math.floor(c_width/225))-20)};ObserveResize.getInstance().add("resize_block_category_prew",fn)}).call(this)});
            -else
              - categories.each do |category|
                .category_box_x
                  %p.title
                    =link_to category.name, category_path(category.link_rewrite, format: :html, page: nil), title: category.name
                    %span 
                      =link_to 'показать все >>', category_path(category.link_rewrite, format: :html, page: nil)
                  .wrap
                    =render partial: 'web/products/preview', collection: category.products.joins(:brand).select('products.id, products.name, products.link_rewrite, products.cover_id, products.price, products.status, products.brand_id, brands.name AS `brand_name`, products.ratio, products.ratio_u, products.discount_type_id, products.discount_value').order_stock.includes(:cover).limit(7), as: :product
                  %p.other
                    =link_to 'показать все товары из каталога '+category.name, category_path(category.link_rewrite, format: :html, page: nil), title: category.name
                .separator_category_box_x
              :javascript
                $(document).ready(function(){
                  ObserveResize.getInstance().add('resize_block_category_products',Helper.resize_block_category_products)
                })
          -else
            =render file: 'web/products/index', locals: {products: @products, query: @query}
          -unless params[:filters][:brands] or params[:filters][:types] or params[:filters][:sort] or params[:page]
            .category_description
              =raw @category.description
         
      .columnLeft
        -categories = @category.self_and_siblings.select('id,name,link_rewrite, lft, rgt, products_visible').where('products_visible > 0').public if categories.empty?

        =render partial: 'web/products/filters/categories_for_categories', locals: { categories: categories }
        .facet_search
          %form.form{method: :get, action: category_path(@category.link_rewrite, format: :html)}
            -if params[:sort]
              %input{type: :hidden, name: :sort, value: params[:sort]}
            -if @query.facet(:type_id).rows[1]
              .facet_box
                %a.remove_this_filter{href: '#', title: "Снять галочки со всех типов"}
                  %i.icon-remove
                .title
                  %span
                    %a{href: types_path(:html), title: 'Посмотреть все типы товаров'}
                      Типы
                %ul
                  -ProductsType.order(:name).select([:id, :name]).find(@query.facet(:type_id).rows.map{|x| x.value}).each do |type|
                    %li 
                      %label.checkbox
                        %input{type: :checkbox, name: 'filters[types][]', value: type.id, checked: params[:filters][:types].to_a.include?(type.id.to_s)}
                        %a{href: category_path(@category.link_rewrite, format: :html, filters: {types:[type.id]}, sort: params[:sort], page: nil)}
                          =type.name                        
            -if @query.facet(:brand_id).rows[1]            
              .facet_box.brands
                %a.remove_this_filter{href: '#', title: "Снять галочки со всех брендов"}
                  %i.icon-remove
                .title
                  %span
                    %a{href: brands_path(:html), title: 'Посмотреть все бренды'}
                      Бренды
                %ul
                  -Brand.order(:name).select([:id, :name]).find(@query.facet(:brand_id).rows.map{|x| x.value}).each do |brand|
                    %li 
                      %label.checkbox
                        %input{type: :checkbox, name: 'filters[brands][]', value: brand.id, checked: params[:filters][:brands].to_a.include?(brand.id.to_s)}
                        =brand.name
            -if @properties.count > 0
              #facet_search
                -@properties.each do |prop|
                  -if @query.facet(:properties,prop.id).rows.count > 1
                    .facet_box  
                      %a.remove_this_filter{href: '#', title: "Снять галочки для #{prop.name}"}
                        %i.icon-remove
                      .title
                        %span
                          =prop.name
                      -values = @query.facet(:properties,prop.id).rows.sort_by{|x| x.value}.partition{|v| !v.count.zero?} 
                      %ul
                        -(values[0] + values[1]).each do |data|
                          %li
                            -if data.count.zero?
                              %label.checkbox.muted
                                %input{disabled: true, name: "filters[#{prop.id}][]", type: :checkbox, value: data.value}
                                =raw "#{data.value} #{prop.unit} (#{data.count})"
                            -else
                              %label.checkbox
                                %input{checked: params[:filters][prop.id.to_s].to_a.include?(data.value), name: "filters[#{prop.id}][]", type: :checkbox, value: data.value}
                                =raw "#{data.value} #{prop.unit} (#{data.count})"
            %button#clean_facet_form.btn{type: :reset}
              %i.icon-remove
              Снять все
            %button.btn.btn-info{type: :submit}
              %i.icon-filter.icon-white 
              Фильтр
      .clearfix.clear
:javascript
  $(document).ready(function(){
    setTimeout(function(){
      $.post('/i_category_view/#{@category.id}')
    },7000)
    $('.facet_box .remove_this_filter').click(function(){
      $(this).parents('.facet_box:first').find('input:checked').prop('checked', false)
      return false;
    })
    $('#clean_facet_form').click(function(){
      $('#facet_search, .facet_box.brands').find('input:checked').prop('checked', false)
      return false;
    })

  })