config/routes.rb
require 'sidekiq/web'
# == Route Map (Updated 2013-02-05 08:34)
#

Sm::Application.routes.draw do

  root to: 'web/home#index', url: 'samara-market.com'
  scope module: :web  do

    controller :categories, path: 'catalog', format: false do
      get '/:category_id(/page/:page)' => redirect{|params| "/catalog/#{params[:category_id]}.html"}
    end

    controller :notification, path: :notification, format: false do
      post :qiwi, action: :qiwi
    end

    controller :categories, path: 'catalog', format: true, constraints: {format: /(html)/} do
      get '/:category_id(/page/:page)', action: :show, as: :category
      get '/', action: :index, as: :categories
    end
    get 'catalog'  => redirect{|params| "/catalog.html"}
    resources :orders, only:[:new, :create, :index, :show]


    controller :cart do
      get 'cart', action: :index, format: true, constraints: {format: /(html)/}
      post 'cart/set_count', action: :set_count, as: 'cart_set_count'
      put 'cart/push', action: :push, as: 'add_to_cart'
      delete 'cart/pop', action: :pop, as: 'remove_from_cart'
      delete 'cart/destroy_products', action: :destroy, as: 'destroy_from_cart'
    end

    controller :brand, format: true, constraints: {format: /(html)/} do
      get '/brands/:id', action: :show, as: :brand
      get '/brands/:brand_id/products(/page/:page)', action: :products, as: 'brand_products'
      get '/brands', action: :index, as: :brands
    end

    controller :types, format: true, constraints: {format: /(html)/} do
      get '/types/:id', action: :show, as: :type
      get '/types/:type_id/products(/page/:page)', action: :products, as: 'type_products'
      get '/types', action: :index, as: :types
    end
    resources :addresses, only: [:index, :update, :destroy, :edit, :new, :create]

    resources :contacts, only: [:index, :create], format: true, constraints: {format: /(html)/}
    get '/viewed_products', constraints: {format: /(html)/}, format: true, controller: :categories, action: :viewed, as: :viewed_products
    get '/discounts(/page/:page)', constraints: {format: /(html)/}, format: true, controller: :categories, action: :discounts, as: :discounts

    resources :products, only: [:show], path: 'product',
      format: true, constraints: {format: /(html)/} do
      resources :reviews, only: [:create], format: false, constraints: {format: nil} do |variable|
        post '/vote_up', action: :vote_up
        post '/vote_down', action: :vote_down
        collection do
          get '/is_edit', action: 'edit?'
          delete '/', action: :destroy
        end
      end
    end

    controller :search, format: true, constraints: {format: /(html)/} do
      get '/search', action: :index, as: :search
    end


    controller :sessions do
      get '/user/is_auth', action: 'auth?'
      get '/user/logout', action: 'logout'
      post '/user/login', action: 'login'
      get '/user/login', action: 'login_page'
      match '/auth/:provider/callback', action: 'oauth'
    end

    controller :user do
      get '/user', action: :index
      post '/user', action: :create
      put '/user', action: :update, as: :update_user
      get '/user/data_verified/:field', action: :data_verified?, as: :data_verified_field, constraints: {field: /(phone|email)/}
      post '/user/data_verified/:field', action: :data_verified, constraints: {field: /(phone|email)/}, as: :data_verified
      get '/recovery_password', as: :recovery_password, action: :recovery_password
      post '/recovery_password', action: :recovery_password!
      post '/update_password', action: :update_password
    end

    controller :sitemap do
      get '/sitemap', action: :index, format: true, constraints: {format: /(xml)/}, as: 'sitemap'
      get '/sitemap_products', action: :products, format: true, constraints: {format: /(xml)/}, as: 'sitemap_products'
      get '/sitemap_categories', action: :categories, format: true, constraints: {format: /(xml)/}, as: 'sitemap_categories'
      get '/sitemap_brands', action: :brands, format: true, constraints: {format: /(xml)/}, as: 'sitemap_brands'
    end

    controller :static_content, format: true, constraints: {format: /(html)/} do
      get '/public_offer', action: 'public_offer'
      get '/privacy_policy', action: 'privacy_policy'
      get '/return_of_goods', action: 'return_of_goods'
      
    end

    controller :delivery, format: true, constraints: {format: /(html)/} do
      get '/delivery', action: :index, as: :delivery
    end

    controller :payment, format: true, constraints: {format: /(html)/} do
      get '/payments', action: :index, as: :payments
    end

  end


  namespace :admin, path: 'the_simpsons_admin' do

    resources :categories, only: [:index, :create, :update, :destroy, :show] do
      resources :adwords, controller: 'CategoriesAdwords' do
        post 'image', action: 'image'
        post 'background', action: 'background'
        post 'cover', action: 'cover'
        post :position, action: :position
      end
      collection do
        put ':id/position', action: :position
        get ':id/products', action: :products
      end
    end
    resources :adwords, only: [:index]
    resources :products_types, only: [:index, :create, :update, :destroy, :show] do
      get :products, action: :products
      resources :type_property, only: [:index, :create, :update, :destroy, :show] do
        collection do
          post ':id/position', action: :position
        end  
      end
    end

    resources :products_suppliers, only: [:index, :create, :update, :destroy, :show] do
      get :products, action: :products
    end
    resources :brands, only: [:index, :create, :update, :destroy, :show] do
      post 'logo', action: 'upload_logo'
      delete  'logo', action: 'destroy_logo'
      get :products, action: :products 
    end
    resources :products_groups, only: [:index, :create, :update, :destroy, :show] do
      get :products, action: :products
    end
    resources :products, only: [:index, :create, :update, :destroy, :show] do
      put :discount, action: 'create_discount'
      delete :discount, action: 'destroy_discount'
      put :item, action: 'create_item'
      delete 'item/:id', action: 'destroy_item'
      resources  :images, controller: :product_image , only: [:create, :destroy] do
        put :cover, action: :cover
        post :position, action: :position
      end
      resources :products_property, only: [:create, :update, :destroy] do 
        resources :products_property_value, only: [:create, :update, :destroy]
      end

      collection do
        put ':id/categories', action: :set_categories
        get ':id/categories', action: :get_categories
      end   
    end
    resources :articles, only: [:index, :update, :show, :create, :destroy] do
      post '/image', action: :image_upload
      delete '/image', action: :image_destroy
      get '/images', action: :images
    end
    resources :orders, only: [:index, :update, :show] do
      get '/bill', action: :bill
      get '/invoice', action: :invoice
      put :bil_qiwi, action: :bil_qiwi
    end
    controller :main do
      get '/login', as: :login, action: :login
      post '/login', action: :auth
      get '/logout', as: :logout, action: :logout
      get '/expire_sitemap', as: :expire_sitemap, action: :expire_sitemap
    end
    get 'properties_values', controller: :ProductsProperty , action: 'properties_values'
    root to: 'main#index' 

  end
  

end

app/models/user.rb
# encoding: UTF-8
# == Schema Information
#
# Table name: users
#
#  id             :integer          not null, primary key
#  first_name     :string(32)
#  last_name      :string(32)
#  middle_name    :string(32)
#  email          :string(64)
#  email_verified :boolean
#  phone          :string(10)
#  phone_verified :boolean
#  cart_id        :integer
#  note           :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :middle_name, :phone, as: :user

  attr_accessible :email, :first_name, :last_name, :middle_name, :note, :phone, :phone_verified, :email_verified, as: :admin

  strip_attributes :email, :email_verified, :first_name, :last_name, :middle_name, :phone, :phone_verified

  validates :first_name, :last_name, :middle_name,
    format: { 
      with: /\A[А-яёЁ'\-]+\z|\A\z/,
      message: 'может содержать только буквы русского алфавита, дефис и знак апострофа'
    },
    length: {
      maximum: 32,
      too_long: 'максимальное количество символов - 32'
    }

  validates :note, length: { maximum: 400 }, format: { 
    with: /\A[A-zА-яёЁ &0-9()\-+,.]+\z|\A\z/}

  validates :email, if: 'email?',
    format: {
      with: /\A([^@\\\/\s]+)@((?:[-a-z0-9]+\.)+[a-z]{1,})\z/i,
      message: 'не подходит под формат, обратитесь в тех.поддержку'
    },
    length: {
      maximum: 64,
    }

  validates :phone,
    length: {
      is: 10,
      message: 'телефон только мобильный, 10 цифер без кода страны'
    },
    numericality: {
      only_integer: true
    }, if: 'phone?'

  has_many :addresses, class_name: 'UserAddress', dependent: :destroy

  has_many :auths, class_name: 'UserAuth', dependent: :destroy

  has_many :orders

  has_many :verifieds, class_name: 'UserDataVerified'

  belongs_to :cart

  before_update :verified
  before_update :auth_login

  def full_name
    self.last_name.to_s+' '+self.first_name.to_s+' '+self.middle_name.to_s
  end


  def verified
    if self.email_changed?
      self.email_verified = false 
      self.verifieds.where(field: self.verifieds.klass::FIELDS[:email]).update_all(exp: true)
    end
    if self.phone_changed?
      self.phone_verified = false
      self.verifieds.where(field: self.verifieds.klass::FIELDS[:phone]).update_all(exp: true)
    end  
    self
  end
  def auth_login
    if self.phone_changed?
      auth = self.auths.where(provider: self.auths.klass::PROVIDERS[:sm]).first
      if auth
        auth.uid = self.phone
        if auth.save
          return true
        else
          self.valid?
          auth.errors.each {|attribute, errors_array| self.errors.add attribute, errors_array  }
          return false
        end 
      end
    end
    true
  end
end

app/controllers/web/user_controller.rb
# encoding: UTF-8
class Web::UserController < Web::ApplicationController
  
  before_filter :only_user, only: [:index, :update, :edit, :data_verified, :data_verified?, :update_password ]
  before_filter :except_user, only: [:recovery_password, :recovery_password! ]

  def index
    @user = current_session.user
  end

  def create
    user = User.new({first_name: params[:first_name], phone: params[:phone]},as: :user)
    auth = UserAuth.new(provider:UserAuth::PROVIDERS[:sm], uid: user.phone, password:params[:password])
    user.cart  = current_cart if current_cart?
    auth.valid?
    begin
      User.transaction do
        user.save!
        auth.user_id = user.id
        auth.save!
        if session_regenerate == false
          raise Exception
        end
        current_session.user_id = user.id
        current_session.save
      end
    rescue ActiveRecord::RecordInvalid => e
      render ({json: user.errors.messages.merge(auth.errors.messages), status: :unprocessable_entity})
      return
    rescue Exception => e
      puts e
      head status: :not_acceptable 
      return 
    end
    

    head status: :ok
    
  end

  def update
    @user = current_session.user
    attributes = {last_name: params[:last_name], 
      first_name: params[:first_name],
      middle_name: params[:middle_name],
      email: params[:email],
      phone: params[:phone]}

    if @user.update_attributes(attributes, as: :user)
      respond_to do |format|
        format.html {
          flash[:success] = t('user.success.update')
          redirect_to user_url
        }
        format.js {}
      end

    else
      respond_to do |format|
        format.html {
          render 'index'
        }
        format.js {}
      end
    end
  end

  def data_verified

    field = UserDataVerified::FIELDS[params[:field].to_sym]

    return data_verified_error t('data_verified.error.field') if field.nil?

    return data_verified_error t('data_verified.error.field_blank', field: User.human_attribute_name(params[:field])) if current_session.user[params[:field].to_sym].blank?

    verified = current_session.user.verifieds.where(field: field).where('updated_at > ?', 10.minute.ago).last

    return data_verified_error t('data_verified.error.timeout', min: ((10.minutes - (Time.now - verified.updated_at))/60).to_i ,timeout: Russian.p(((10.minutes-(Time.now - verified.updated_at))/60).to_i, 'минута', 'минуты', 'минут')) if verified

    verified = current_session.user.verifieds.where(field: field).where('created_at > ?', 1.day.ago).last

    if verified
      return data_verified_error t('data_verified.error.maximum',  field: User.human_attribute_name(params[:field]), count: verified.class::BANS[params[:field].to_sym]) if verified.attempts >= verified.class::BANS[params[:field].to_sym]
      verified.attempts = verified.attempts.to_i.next
      verified.exp = false
      verified.generate_token        


    else
      verified = UserDataVerified.new do |udv|
        udv.user = current_session.user
        udv.field = field
        udv.attempts = 0 
      end
    end
    begin
      verified.save!
    rescue Exception => e
      logger.error e
      return data_verified_error t('data_verified.error.system')
    end

    flash[:data_verified_success] = t("data_verified.success.#{params[:field]}", addr: current_session.user[params[:field]] )
    redirect_to user_url

  end

  def data_verified?
    field = UserDataVerified::FIELDS[params[:field].to_sym]
    
    return data_verified_error t('data_verified.error.field') if field.nil?
    
    return data_verified_error t('data_verified.error.already_verified', field: User.human_attribute_name(params[:field]), addr: current_session.user[params[:field]]) if current_session.user[params[:field]+'_verified']

    verified = current_session.user.verifieds.where(field: field, exp: false).where('updated_at > ?', 1.day.ago).last

    if verified
      if verified.compare_token(params[:token])
        flash[:data_verified_success] = t("data_verified.success.#{params[:field]}_verified", addr: current_session.user[params[:field]])
        return redirect_to user_url
      else
        return data_verified_error t('data_verified.error.token_invalid',  field: User.human_attribute_name(params[:field]), addr: current_session.user[params[:field]])
      end
    else
      return  data_verified_error t('data_verified.error.token_exp',  field: User.human_attribute_name(params[:field]), addr: current_session.user[params[:field]])
    end

  end

  def recovery_password
    @errors = []
    @recovery = nil
    @captcha = YaCleanweb.captcha
  end

  def recovery_password!
    @errors = []
    @recovery = nil
    @captcha = YaCleanweb.captcha
    if params[:captcha].is_a?(Hash) and params[:captcha][:value] and params[:captcha][:uid]
      begin
        @errors << t('errors.recovery_password.captcha_wrong') unless YaCleanweb.captcha_valid?(params[:captcha][:uid], params[:captcha][:value])
      rescue Exception => e
      end
    else
      @errors << t('errors.recovery_password.captcha_wrong')
    end
  
    if @errors.empty?
      user = User.where(phone: params[:phone]).first
      @errors << t('errors.recovery_password.user_not_found') if user.nil? 
      
      if @errors.empty?
        auth = user.auths.where(provider: UserAuth::PROVIDERS[:sm]).first

        @errors << t('errors.recovery_password.auth_not_found') if auth.nil?

        if @errors.empty?
          @recovery = UserPasswordRecovery.get(auth)
          @errors << t('errors.recovery_password.limit',time: (@recovery.exp_minutes.to_i/60), time_s: Russian.p(@recovery.exp_minutes.to_i/60, 'минуту', 'минуты', 'минут')) if @recovery.ban?

          if @errors.empty?
            @recovery.regenerate_password!
          end

        end

      end

    end
    if @errors.any?
      render template: 'web/user/recovery_password'
    else
      flash[:phone] = @recovery.user_auth.user.phone
      flash[:success] = t('recovery_password.success', phone: @recovery.user_auth.user.phone )
      redirect_to user_login_url
    end
  end

  def update_password

    return update_password_error t('update_user_password.errors.passwords_same') if params[:password] == params[:old_password]
    return update_password_error t('update_user_password.errors.retry_password')  unless params[:password] == params[:retry_password]
    
    auth = current_session.user.auths.where(provider: UserAuth::PROVIDERS[:sm]).first
    
    return update_password_error t('update_user_password.errors.not_update') if auth.nil?
    
    auth.password = params[:password]
    
    if auth.save
      flash[:update_password_success] = t('update_user_password.success')
      redirect_to user_url(anchor: 'user_password_form')
    else
      return update_password_error auth.errors.full_messages
    end
  end

  private

    def data_verified_error(msg)
      flash[:data_verified_error] = msg
      redirect_to user_url
    end

    def update_password_error(msg)
      flash[:update_password_error] = msg
      redirect_to user_url(anchor: 'user_password_form')
    end

end

app/views/web/user/index.html.haml
- content_for(:head) do

  %title
    =@user.full_name
    профиль на Самара-Маркет

  %meta{name: 'description', content: 'Ваш профиль Самара-Маркет'}

  :javascript
    config.navigation = false;
%script
  $(document).ready(function(){window.Helper.standart_page()})

.standart_page
  .pageWrap
    .pageContainer
      .columnRight
        .content
          =render partial: 'web/navigations/profile'
          #user_profile
            %h1 Ваш профиль
            %form#user_profile_form.form-horizontal{action: update_user_path, method: :post}
              -if @user.errors.any? or flash[:data_verified_error]
                .alert.alert-error
                  %button.close{type: :button, data:{dismiss: :alert}}
                    &times;
                  -if @user.errors.any?
                    %h4
                      =Russian.p(@user.errors.count, 'Найдена', 'Найдено', 'Найдено')
                      =@user.errors.count
                      =Russian.p(@user.errors.count, 'ошибка.', 'ошибки.', 'ошибок.')
                    %br
                    %p
                      Профиль не сохранён.
                    %ul
                      - @user.errors.full_messages.each do |error|
                        %li 
                          =error
                  -else flash[:data_verified_error]
                    =flash[:data_verified_error]

              -if flash[:data_verified_success]
                .alert.alert-success
                  %button.close{type: :button, data:{dismiss: :alert}}
                    &times;
                  = flash[:data_verified_success]

              %input{name: :_method, type: :hidden, value: :put}
              %input{name: 'authenticity_token', type: :hidden, value: form_authenticity_token }
              %input{name: :id, type: :hidden, value: @user.id}
              .control-group{class: ('error' if @user.errors.messages[:last_name])}
                %label.control-label{for: 'form_user_edit_last_name'}
                  Фамилия:
                .controls
                  %input#form_user_edit_last_name{name: :last_name, type: :text, value: @user.last_name}
              .control-group{class: ('error' if @user.errors.messages[:first_name])}
                %label.control-label{for: 'form_user_edit_first_name'}
                  Имя:
                .controls
                  %input#form_user_edit_first_name{name: :first_name, type: :text, value: @user.first_name}
              .control-group{class: ('error' if @user.errors.messages[:middle_name])}
                %label.control-label{for: 'form_user_edit_middle_name'}
                  Отчество:
                .controls
                  %input#form_user_edit_middle_name{name: :middle_name, type: :text, value: @user.middle_name}
              .control-group{class: ('error' if @user.errors.messages[:email])}
                %label.control-label{for: 'form_user_edit_email'}
                  E-mail:
                .controls
                  %input#form_user_edit_email{name: :email, type: :text, value: @user.email}
                  -if !@user.email.blank?
                    -if @user.email_verified
                      %span.badge.badge-success
                        подтвержден
                    -else    
                      %span.badge.badge-important{title: 'Ваш email адрес не подтверждён'}
                        не подтвержден
              .control-group{class: ('error' if @user.errors.messages[:phone])}
                %label.control-label{for: 'form_user_edit_phone'}
                  Телефон:
                .controls
                  %input#form_user_edit_phone{name: :phone, type: :text, value: @user.phone}
                  -if !@user.phone.blank?
                    -if @user.phone_verified
                      %span.badge.badge-success
                        подтвержден
                    -else    
                      -if !@user.phone_verified
                        %span.badge.badge-important{title: 'Ваш номер телефона не подтверждён'}
                          не подтвержден
              .form-actions
                %button.btn.btn-primary{type: :submit}
                  Сохранить
            .row.fly
              -if !@user.phone_verified 
                #user_profile_phone_verified.span12
                  %p 
                    %span.badge.badge-important Ваш номер телефона не подтверждён.
                    Для подтверждения нажмите кнопку, после чего Вам придёт смс с подтверждающим кодом, этот код будет необходимо ввести в появившиеся поле.
                  =button_to 'Запросить код для телефона', data_verified_path(field: :phone), confirm: 'Вы уверены что хотите подтвердить номер телефона '<<@user.phone.to_s, method: :post, class: 'btn'
                - if current_session.user.verifieds.where(field: UserDataVerified::FIELDS[:phone], exp: false).where('created_at > ?', 1.day.ago).last
                  #user_profile_phone_verified_key.span12
                    %form.form-inline{method: :get, action: data_verified_field_path(field: :phone)}
                      %label
                        Код подтверждения номера телефона:
                      %input{type: :text, name: :token}
                      %button.btn.btn-success{type: :submit}
                        активировать
              -if !@user.email_verified and !@user.email.blank?
                #user_profile_email_verified.span12
                  %p 
                    %span.badge.badge-important Ваш email адрес не подтверждён.
                    Для подтверждения нажмите кнопку, после чего Вам придёт письмо на указанный email со специальной ссылкой, по которой будет нужно пройти или же скопировать код подтверждения в появившиеся поле.
                  =button_to 'Запросить код для email', data_verified_path(field: :email), confirm: 'Вы уверены что хотите подтвердить email адрес '<<@user.email.to_s, method: :post, class: 'btn'
                - if current_session.user.verifieds.where(field: UserDataVerified::FIELDS[:email], exp: false).where('created_at > ?', 1.day.ago).last
                  #user_profile_email_verified_key.span12
                    %form.form-inline{method: :get, action: data_verified_field_path(field: :email)}
                      %label
                        Код подтверждения email:
                      %input{type: :text, name: :token}
                      %button.btn.btn-success{type: :submit}
                        активировать
            -if @user.auths.where(provider: UserAuth::PROVIDERS[:sm]).first
              %form#user_password_form.form-horizontal{action: update_password_path, method: :post}
              
                %h3 Изменение пароля
                %input{name: :_method, type: :hidden, value: :post}
                %input{name: 'authenticity_token', type: :hidden, value: form_authenticity_token }
                -if flash[:update_password_error]
                  .alert.alert-error
                    %button.close{type: :button, data:{dismiss: :alert}}
                      &times;
                    -if flash[:update_password_error].is_a?(String)
                      %p= flash[:update_password_error]
                    -else
                      %ul
                        -flash[:update_password_error].each do |error|
                          %li= error
                -if flash[:update_password_success]
                  .alert.alert-success
                    %button.close{type: :button, data:{dismiss: :alert}}
                      &times;
                    %p= flash[:update_password_success]
                .control-group
                  %label.control-label{for: 'user_password_form_old'}
                    Настоящий пароль:
                  .controls
                    %input#user_password_form_old{name: :old_password, type: :password}
                .control-group
                  %label.control-label{for: 'user_password_form_new'}
                    Новый пароль:
                  .controls
                    %input#user_password_form_new{name: :password, type: :password}
                .control-group
                  %label.control-label{for: 'user_password_form_retry'}
                    Повтор пароля:
                  .controls
                    %input#user_password_form_retry{name: :retry_password, type: :password}
                .form-actions
                  %button.btn.btn-primary{type: :submit}
                    Сохранить
      .columnLeft

app/views/web/user/recovery_password.html.haml
- content_for(:head) do

  %title
    Востановление пароля

  %meta{name: 'description', content: 'Востановление пароля для доступа к сайту'}

  :javascript
    config.navigation = false;
%script
  $(document).ready(function(){window.Helper.standart_page()})

.standart_page
  .pageWrap
    .pageContainer
      .columnRight
        .content
          #page_recovery_password
            %h1 Востановление пароля
            %p
              Если Вы забыли свой пароль, то можете воспользоваться этой формой для его изменения.
            %p
              Если Ваш номер телефона зарегестрирован на нашем сайте, то через несколько секунд Вы должны получить смс с новым паролем.
            -if @errors.any?
              .alert.alert-error
                %button.close{type: :button, data:{dismiss: :alert}}
                  &times;
                %ul
                  -@errors.each do |error|
                    %li
                      =error

            .form_for_recovery.well
              %h3 Запросить пароль
              %form#recoveryPasswordForm.form-horizontal{ action: recovery_password_path, method: :post}
                %input{name: :_method, type: :hidden, value: :post}
                %input{name: 'authenticity_token', type: :hidden, value: form_authenticity_token }
                .control-group.phone
                  %label.control-label{for: 'recoveryPasswordFormPhone'}
                    Ваш номер телефона:
                  .controls.input-prepend.phone
                    %span.add-on
                      +7
                    %input#recoveryPasswordFormPhone{type: :text, name: :phone, placeholder: 'Мобильный телефон', value: params[:phone]}
                .control-group.captcha
                  %label.control-label{for: 'recoveryPasswordFormCaptcha'} 
                    %img{src: @captcha[:url], alt: 'Капча'}
                  .controls
                    %input{type: :hidden, name: 'captcha[uid]', value: @captcha[:uid]}
                    %input#recoveryPasswordFormCaptcha{type: :text, name: 'captcha[value]', placeholder: 'Введите символы с картинки'}
                .control-group.submit
                  .controls
                    %button.btn.btn-primary{type: :submit}
                      Получить пароль
      .columnLeft